// Auto-generated utility now in src/develop-scripts/gen-version.js
// Generates src/data/version.ts with current date/time stamp.
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

function nowVersion() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  const y = d.getFullYear();
  const m = pad(d.getMonth() + 1);
  const day = pad(d.getDate());
  const hh = pad(d.getHours());
  const mm = pad(d.getMinutes());
  return `${y}.${m}.${day}-${hh}${mm}`;
}

const version = nowVersion();
const outPath = resolve('src/data/version.ts');
mkdirSync(dirname(outPath), { recursive: true });
const content = `// Auto-generated by src/develop-scripts/gen-version.js\nexport const BUILD_VERSION = '${version}';\n`;
writeFileSync(outPath, content, 'utf8');
console.log(`[gen-version] BUILD_VERSION=${version}`);
